services:
  resources:
    container_name: resources
    image: registry.299natola.fun/resources:latest
    restart: always
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - /Users/miguel/Desktop/personal/cenas:/cenas
